baseURL = 'http://joeridijkstra.dev/'
languageCode = 'en-us'
title = 'Joeri Dijkstra'
theme = 'etch'

[params]
dark = "off"
copyright = "Copyright Â© 2025 Joeri Dijkstra"
description = "Personal website"

[menu]
[[menu.main]]
identifier = "about"
name = "about"
title = "about"
url = "/about/"
weight = 20

[[menu.main]]
identifier = "projects"
name = "projects"
title = "projects"
url = "/projects/"
weight = 20
